# Generated by Django 2.1.5 on 2019-04-10 21:56

from django.db import migrations


#list of dictionary
SEMESTERS = [
    {
        'semester_name': '2019 - Summer',
    },
    {
        'semester_name': '2019 - Fall',
    },
    {
        'semester_name': '2020 - Spring',
    },
    {
        'semester_name': '2020 - Summer',
    },
    {
        'semester_name': '2020 - Fall',
    },
]


def add_semester_data(apps, schema_editor):
    semester_model_class = apps.get_model('courseinfo', 'Semester')
    #go through the data structure
    for semester in SEMESTERS:
        semester_object = semester_model_class.objects.create(
            semester_name=semester['semester_name'], # semester_ name reference SEMESTERS
        )


def remove_semester_data(apps, schema_editor):
    semester_model_class = apps.get_model('courseinfo', 'Semester')
    for semester in SEMESTERS:
        semester_object = semester_model_class.objects.get( #retrived
            semester_name=semester['semester_name']
        )
        semester_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        #link to migration 3
        ('courseinfo', '0003_auto_20190410_2147'),
    ]

    operations = [
        migrations.RunPython(
            #two functions, control forward and backword
            add_semester_data,
            remove_semester_data
        )
    ]
