# Generated by Django 2.1.5 on 2019-04-10 22:52

from django.db import migrations, models


#dic one row in a table, peroid time is not a field
PERIODS = [
    {
        "period_sequence": 10,
        "period_name": "Spring",
    },
    {
        "period_sequence": 20,
        "period_name": "Summer",
    },
    {
        "period_sequence": 30,
        "period_name": "Fall",
    },
    {
        "period_sequence": 9999,
        "period_name": "TemporaryValue",
    },
]


def add_period_data(apps, schema_editor):
    period_class = apps.get_model('courseinfo', 'Period')
    for this_period in PERIODS:
        period_object = period_class.objects.create( #create objects
            period_sequence=this_period['period_sequence'],
            period_name=this_period['period_name']
        )


def remove_period_data(apps, schema_editor):
    period_class = apps.get_model('courseinfo', 'Period')
    # go through the list, uniquely identify
    for this_period in PERIODS:
        period_object = period_class.objects.get(
            period_sequence=this_period['period_sequence']
        )
        period_object.delete()


YEARS = [
    {
        'year': 2018,
    },
    {
        'year': 2019,
    },
    {
        'year': 2020,
    },
    {
        'year': 9999,
    },

]


def add_year_data(apps, schema_editor):
    year_model_class = apps.get_model('courseinfo', 'Year')
    for this_year in YEARS:
        year_object = year_model_class.objects.create(
            year=this_year['year']
        )


def remove_year_data(apps, schema_editor):
    year_model_class = apps.get_model('courseinfo', 'Year')
    for this_year in YEARS:
        year_object = year_model_class.objects.get(
            year=this_year['year']
        )
        year_object.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0004_semester_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('period_id', models.AutoField(primary_key=True, serialize=False)),
                ('period_sequence', models.IntegerField(unique=True)),
                ('period_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'ordering': ['period_sequence'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['year'],
            },
        ),

        migrations.RunPython(
            add_period_data,
            remove_period_data
        ),


        migrations.RunPython(
            add_year_data,
            remove_year_data
        ),
    ]
